---
- name: Stop VM from a template in vcenter
  hosts: localhost
  connection: local
  gather_facts: no
  become: true
  vars:
    vcenter_ip: 10.150.4.22
    vcenter_username: USP01\patelr32
    vcenter_password: xxxxxx
    vm_name: computetestvm
    cluster_name: USDC04
  tasks:
    - name: Delete VM
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cluster: "{{ cluster_name }}"
        name: "{{ vm_name }}"
        state: absent
      delegate_to: localhost